# Generated by Django 2.2.17 on 2020-11-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=7)),
                ('score', models.PositiveSmallIntegerField()),
                ('play_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ranking',
                'verbose_name_plural': 'ranking',
                'db_table': 'ranking',
                'ordering': ['-score', '-play_date'],
            },
        ),
    ]
